### ISSUE TITLE
Support for responses with schema type "array"

### ISSUE THREAD

**Issue by esteiner** [phiz71/vertx-swagger#3] opened 2016-12-05 13:08 UTC
It seems that the SwaggerRouter class doesn't support responses with a schema type of "array". 

My simple fix (for SwaggerRouter::configureRoute) looks like:

    private static void configureRoute(Route route, String serviceId, Operation operation, EventBus eventBus) {
        Optional.ofNullable(operation.getConsumes()).ifPresent(consumes -> consumes.forEach(route::consumes));
        Optional.ofNullable(operation.getProduces()).ifPresent(produces -> produces.forEach(route::produces));

        route.handler(context -> {
            try {
                JsonObject message = new JsonObject();
                operation.getParameters().forEach(parameter -> {
                    String name = parameter.getName();
                    Object value = PARAMETER_EXTRACTORS.get(parameter.getIn()).extract(name, parameter, context);
                    message.put(name, value);
                });
                String type = operation.getResponses().get("200").getSchema().getType();
                if ("array".equals(type)) {
                	eventBus.<JsonArray> send(serviceId, message, operationResponse -> {
                		if (operationResponse.succeeded()) {
                			if(operationResponse.result().body() != null)
                				context.response().end(operationResponse.result().body().encode());
                			else
                				context.response().end();
                		} else {
                			internalServerErrorEnd(context.response());
                		}
                	});
                }
                else {
	                eventBus.<JsonObject> send(serviceId, message, operationResponse -> {
	                    if (operationResponse.succeeded()) {
	                        if(operationResponse.result().body() != null)
	                            context.response().end(operationResponse.result().body().encode());
	                        else
	                            context.response().end();
	                    } else {
	                        internalServerErrorEnd(context.response());
	                    }
	                });
                }
            } catch (RuntimeException e) {
                VERTX_LOGGER.debug("sending Bad Request", e);
                badRequestEnd(context.response());
            }
            
        });

    }

As an example I am using the petstore swagger.json API together with the vertx-swagger-codegen generator. In the generated ApiVerticle I had to fix the code as well. During runtime I get the following error:

Unhandled exception 
java.lang.ClassCastException: io.vertx.core.json.JsonArray cannot be cast to io.vertx.core.json.JsonObject
	at io.vertx.ext.swagger.router.SwaggerRouter.lambda$null$5(SwaggerRouter.java:81)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$convertHandler$125(EventBusImpl.java:333)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handleMessage(HandlerRegistration.java:207)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:201)

**Comment by phiz71** [comment] 2016-12-18 15:34
I will try to reproduce your problem. For now, i don't see what's going wrong.

**Comment by phiz71** [comment] 2016-12-20 21:09
In the petstore example, which resource do you call ? Because it seems that the consumer is sending a JsonArray in the eventBus whereas your handler is waiting for a JsonObject.
It would mean that it is the "else" condition which is activated.

**Comment by esteiner** [comment] 2016-12-21 08:10
I am calling /pet/findByStatus. My Java implementation is return in a list of pets (List<Pet>). I had to change the generated PetApiVerticle as well to 

message.reply(new JsonArray(Json.encode(result)));

**Comment by phiz71** [comment] 2017-01-02 14:09
I didn't manage to reproduce your issue. However, I've implemented the petstore example as you did, and I don't have any problem.
I've commited modifications on develop branch. Could you check if it changes something for you ?

**Comment by inikolaev** [comment] 2017-02-11 09:23
I would like to add to this - in our use-case we also need to be able to return result as a `string` (e.g. `CSV` file).

**Comment by phiz71** [comment] 2017-02-11 21:23
Do you mean that your REST resource send back a String ? Or is it only the event consumer you want to answer this ?
If you are in the second case, i think @brittcagnina has done something like this in [his fork](https://github.com/ElyxorCorp/vertx-swagger/commit/a42a6033b793313644e2cf13bc5f768df5669a4a). I think I will do the same. It may be a good idea.

**Comment by inikolaev** [comment] 2017-02-11 21:30
Yes, that change in that fork is exactly what I need.

I was also thinking about propagating HTTP headers from the consumer. One of the use-cases is when no resource found I would like to return `404` or in some cases I may need to return `204` status code or some other header, like `Content-Type` for example.

I can create a separate issue for that is you like.

**Comment by phiz71** [comment] 2017-02-12 08:11
I've committed some changes on the develop branch.
I think I will have to update the generator to adapt the way Verticle are generated. I mean, handle the "produces" tag in swagger to change the result.

**Closed** 2017-02-16 21:19 UTC
