### ISSUE TITLE
Swagger pattern validation

### ISSUE THREAD

**Issue by Lakshmihm** [phiz71/vertx-swagger#54] opened 2017-07-18 11:14 UTC
Hi,

Swagger contract allows  Patterned fields, which declare a regex pattern for the field name
It would be really elegant if SwaggerRouter could implement this validation. Currently we are doing this regex validation in the code, but doing it as part of the swagger contract is more elegant.

**Comment by phiz71** [comment] 2017-07-18 12:02
Hi, I think it is quite the same thing as #26 .
For the moment, I'm thinking of two possible implementations :
1. include validation in each `xxxParameterExtractor`
2. add some kind of handler in the router configuration which would validate the incoming request before sending the parameters on the eventBus.

I don't have much time to work on it these days, but feel free to propose something :smile:

**Comment by Lakshmihm** [comment] 2017-07-18 12:20
Thanks for the reply

yes both options makes sense to me. I would prefer to have all the validation in the xxxParameterExtractor 

I understand you might be busy :) . Really good project. I would like to contribute as well. Thanks

**Comment by phiz71** [comment] 2017-07-20 20:32
Duplicate of #26

**Closed** 2017-07-20 20:32 UTC
Labels: duplicate
